// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: encounter_service.proto

package encounter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definicija enumeracije EncounterType
type EncounterType int32

const (
	EncounterType_SOCIAL          EncounterType = 0
	EncounterType_HIDDEN_LOCATION EncounterType = 1
	EncounterType_MISC            EncounterType = 2
)

// Enum value maps for EncounterType.
var (
	EncounterType_name = map[int32]string{
		0: "SOCIAL",
		1: "HIDDEN_LOCATION",
		2: "MISC",
	}
	EncounterType_value = map[string]int32{
		"SOCIAL":          0,
		"HIDDEN_LOCATION": 1,
		"MISC":            2,
	}
)

func (x EncounterType) Enum() *EncounterType {
	p := new(EncounterType)
	*p = x
	return p
}

func (x EncounterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncounterType) Descriptor() protoreflect.EnumDescriptor {
	return file_encounter_service_proto_enumTypes[0].Descriptor()
}

func (EncounterType) Type() protoreflect.EnumType {
	return &file_encounter_service_proto_enumTypes[0]
}

func (x EncounterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncounterType.Descriptor instead.
func (EncounterType) EnumDescriptor() ([]byte, []int) {
	return file_encounter_service_proto_rawDescGZIP(), []int{0}
}

type EncounterStatus int32

const (
	EncounterStatus_EXECUTION_ACTIVE   EncounterStatus = 0
	EncounterStatus_EXECUTION_DRAFT    EncounterStatus = 1
	EncounterStatus_EXECUTION_ARCHIVED EncounterStatus = 2
)

// Enum value maps for EncounterStatus.
var (
	EncounterStatus_name = map[int32]string{
		0: "EXECUTION_ACTIVE",
		1: "EXECUTION_DRAFT",
		2: "EXECUTION_ARCHIVED",
	}
	EncounterStatus_value = map[string]int32{
		"EXECUTION_ACTIVE":   0,
		"EXECUTION_DRAFT":    1,
		"EXECUTION_ARCHIVED": 2,
	}
)

func (x EncounterStatus) Enum() *EncounterStatus {
	p := new(EncounterStatus)
	*p = x
	return p
}

func (x EncounterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncounterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_encounter_service_proto_enumTypes[1].Descriptor()
}

func (EncounterStatus) Type() protoreflect.EnumType {
	return &file_encounter_service_proto_enumTypes[1]
}

func (x EncounterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncounterStatus.Descriptor instead.
func (EncounterStatus) EnumDescriptor() ([]byte, []int) {
	return file_encounter_service_proto_rawDescGZIP(), []int{1}
}

// Definicija DTO-a CoordinateDto
type CoordinateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *CoordinateDto) Reset() {
	*x = CoordinateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CoordinateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinateDto) ProtoMessage() {}

func (x *CoordinateDto) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinateDto.ProtoReflect.Descriptor instead.
func (*CoordinateDto) Descriptor() ([]byte, []int) {
	return file_encounter_service_proto_rawDescGZIP(), []int{0}
}

func (x *CoordinateDto) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CoordinateDto) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

// Definicija DTO-a EncounterDto
type EncounterDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                            string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                          string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description                   string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Coordinates                   *CoordinateDto  `protobuf:"bytes,4,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	Xp                            int32           `protobuf:"varint,5,opt,name=xp,proto3" json:"xp,omitempty"`
	Status                        EncounterStatus `protobuf:"varint,6,opt,name=status,proto3,enum=EncounterStatus" json:"status,omitempty"`
	Type                          EncounterType   `protobuf:"varint,7,opt,name=type,proto3,enum=EncounterType" json:"type,omitempty"`
	Range                         int32           `protobuf:"varint,8,opt,name=range,proto3" json:"range,omitempty"`
	ImageUrl                      string          `protobuf:"bytes,9,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	MiscEncounterTask             string          `protobuf:"bytes,10,opt,name=misc_encounter_task,json=miscEncounterTask,proto3" json:"misc_encounter_task,omitempty"`
	SocialEncounterRequiredPeople int32           `protobuf:"varint,11,opt,name=social_encounter_required_people,json=socialEncounterRequiredPeople,proto3" json:"social_encounter_required_people,omitempty"`
	CheckpointId                  int64           `protobuf:"varint,12,opt,name=checkpoint_id,json=checkpointId,proto3" json:"checkpoint_id,omitempty"`
	IsRequired                    bool            `protobuf:"varint,13,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
}

func (x *EncounterDto) Reset() {
	*x = EncounterDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncounterDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncounterDto) ProtoMessage() {}

func (x *EncounterDto) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncounterDto.ProtoReflect.Descriptor instead.
func (*EncounterDto) Descriptor() ([]byte, []int) {
	return file_encounter_service_proto_rawDescGZIP(), []int{1}
}

func (x *EncounterDto) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EncounterDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EncounterDto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EncounterDto) GetCoordinates() *CoordinateDto {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *EncounterDto) GetXp() int32 {
	if x != nil {
		return x.Xp
	}
	return 0
}

func (x *EncounterDto) GetStatus() EncounterStatus {
	if x != nil {
		return x.Status
	}
	return EncounterStatus_EXECUTION_ACTIVE
}

func (x *EncounterDto) GetType() EncounterType {
	if x != nil {
		return x.Type
	}
	return EncounterType_SOCIAL
}

func (x *EncounterDto) GetRange() int32 {
	if x != nil {
		return x.Range
	}
	return 0
}

func (x *EncounterDto) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *EncounterDto) GetMiscEncounterTask() string {
	if x != nil {
		return x.MiscEncounterTask
	}
	return ""
}

func (x *EncounterDto) GetSocialEncounterRequiredPeople() int32 {
	if x != nil {
		return x.SocialEncounterRequiredPeople
	}
	return 0
}

func (x *EncounterDto) GetCheckpointId() int64 {
	if x != nil {
		return x.CheckpointId
	}
	return 0
}

func (x *EncounterDto) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

type GetEncounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetEncounterRequest) Reset() {
	*x = GetEncounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEncounterRequest) ProtoMessage() {}

func (x *GetEncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEncounterRequest.ProtoReflect.Descriptor instead.
func (*GetEncounterRequest) Descriptor() ([]byte, []int) {
	return file_encounter_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetEncounterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateEncounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encounter *EncounterDto `protobuf:"bytes,1,opt,name=encounter,proto3" json:"encounter,omitempty"`
}

func (x *CreateEncounterRequest) Reset() {
	*x = CreateEncounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEncounterRequest) ProtoMessage() {}

func (x *CreateEncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEncounterRequest.ProtoReflect.Descriptor instead.
func (*CreateEncounterRequest) Descriptor() ([]byte, []int) {
	return file_encounter_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEncounterRequest) GetEncounter() *EncounterDto {
	if x != nil {
		return x.Encounter
	}
	return nil
}

type UpdateEncounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encounter *EncounterDto `protobuf:"bytes,1,opt,name=encounter,proto3" json:"encounter,omitempty"`
}

func (x *UpdateEncounterRequest) Reset() {
	*x = UpdateEncounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEncounterRequest) ProtoMessage() {}

func (x *UpdateEncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEncounterRequest.ProtoReflect.Descriptor instead.
func (*UpdateEncounterRequest) Descriptor() ([]byte, []int) {
	return file_encounter_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEncounterRequest) GetEncounter() *EncounterDto {
	if x != nil {
		return x.Encounter
	}
	return nil
}

type DeleteEncounterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteEncounterRequest) Reset() {
	*x = DeleteEncounterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEncounterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEncounterRequest) ProtoMessage() {}

func (x *DeleteEncounterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEncounterRequest.ProtoReflect.Descriptor instead.
func (*DeleteEncounterRequest) Descriptor() ([]byte, []int) {
	return file_encounter_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteEncounterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Poruka za listu EncounterDto objekata
type EncounterDtoList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Encounters []*EncounterDto `protobuf:"bytes,1,rep,name=encounters,proto3" json:"encounters,omitempty"`
}

func (x *EncounterDtoList) Reset() {
	*x = EncounterDtoList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncounterDtoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncounterDtoList) ProtoMessage() {}

func (x *EncounterDtoList) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncounterDtoList.ProtoReflect.Descriptor instead.
func (*EncounterDtoList) Descriptor() ([]byte, []int) {
	return file_encounter_service_proto_rawDescGZIP(), []int{6}
}

func (x *EncounterDtoList) GetEncounters() []*EncounterDto {
	if x != nil {
		return x.Encounters
	}
	return nil
}

// Poruka Empty za metode koje ne zahtevaju parametre
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_encounter_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_encounter_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_encounter_service_proto_rawDescGZIP(), []int{7}
}

var File_encounter_service_proto protoreflect.FileDescriptor

var file_encounter_service_proto_rawDesc = []byte{
	0x0a, 0x17, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x49, 0x0a, 0x0d, 0x43, 0x6f, 0x6f,
	0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x22, 0xd6, 0x03, 0x0a, 0x0c, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x44, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x0b, 0x63,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f,
	0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x78, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x78, 0x70, 0x12, 0x28, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e,
	0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x2e,
	0x0a, 0x13, 0x6d, 0x69, 0x73, 0x63, 0x5f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x5f, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6d, 0x69, 0x73,
	0x63, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x47,
	0x0a, 0x20, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x70, 0x65, 0x6f, 0x70,
	0x6c, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x1d, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c,
	0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65,
	0x64, 0x50, 0x65, 0x6f, 0x70, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x69, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x22, 0x25, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x45, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b,
	0x0a, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x74, 0x6f,
	0x52, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x16, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x65, 0x72, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41, 0x0a, 0x10,
	0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x2d, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x44, 0x74, 0x6f, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x3a, 0x0a, 0x0d, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x4f, 0x43,
	0x49, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x48, 0x49, 0x44, 0x44, 0x45, 0x4e, 0x5f,
	0x4c, 0x4f, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x49,
	0x53, 0x43, 0x10, 0x02, 0x2a, 0x54, 0x0a, 0x0f, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65,
	0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x58, 0x45, 0x43, 0x55,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a,
	0x0f, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x52, 0x41, 0x46, 0x54,
	0x10, 0x01, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x41, 0x52, 0x43, 0x48, 0x49, 0x56, 0x45, 0x44, 0x10, 0x02, 0x32, 0xa9, 0x02, 0x0a, 0x10, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x2c, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x25, 0x0a,
	0x06, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a,
	0x11, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x17,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x17, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x45, 0x6e,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x06,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45,
	0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x1a, 0x11, 0x2e, 0x45, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x44, 0x74, 0x6f,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x65, 0x6e, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_encounter_service_proto_rawDescOnce sync.Once
	file_encounter_service_proto_rawDescData = file_encounter_service_proto_rawDesc
)

func file_encounter_service_proto_rawDescGZIP() []byte {
	file_encounter_service_proto_rawDescOnce.Do(func() {
		file_encounter_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_encounter_service_proto_rawDescData)
	})
	return file_encounter_service_proto_rawDescData
}

var file_encounter_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_encounter_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_encounter_service_proto_goTypes = []interface{}{
	(EncounterType)(0),             // 0: EncounterType
	(EncounterStatus)(0),           // 1: EncounterStatus
	(*CoordinateDto)(nil),          // 2: CoordinateDto
	(*EncounterDto)(nil),           // 3: EncounterDto
	(*GetEncounterRequest)(nil),    // 4: GetEncounterRequest
	(*CreateEncounterRequest)(nil), // 5: CreateEncounterRequest
	(*UpdateEncounterRequest)(nil), // 6: UpdateEncounterRequest
	(*DeleteEncounterRequest)(nil), // 7: DeleteEncounterRequest
	(*EncounterDtoList)(nil),       // 8: EncounterDtoList
	(*Empty)(nil),                  // 9: Empty
}
var file_encounter_service_proto_depIdxs = []int32{
	2,  // 0: EncounterDto.coordinates:type_name -> CoordinateDto
	1,  // 1: EncounterDto.status:type_name -> EncounterStatus
	0,  // 2: EncounterDto.type:type_name -> EncounterType
	3,  // 3: CreateEncounterRequest.encounter:type_name -> EncounterDto
	3,  // 4: UpdateEncounterRequest.encounter:type_name -> EncounterDto
	3,  // 5: EncounterDtoList.encounters:type_name -> EncounterDto
	4,  // 6: EncounterService.Get:input_type -> GetEncounterRequest
	9,  // 7: EncounterService.GetAll:input_type -> Empty
	5,  // 8: EncounterService.Create:input_type -> CreateEncounterRequest
	6,  // 9: EncounterService.Update:input_type -> UpdateEncounterRequest
	7,  // 10: EncounterService.Delete:input_type -> DeleteEncounterRequest
	9,  // 11: EncounterService.GetAllActive:input_type -> Empty
	3,  // 12: EncounterService.Get:output_type -> EncounterDto
	8,  // 13: EncounterService.GetAll:output_type -> EncounterDtoList
	3,  // 14: EncounterService.Create:output_type -> EncounterDto
	3,  // 15: EncounterService.Update:output_type -> EncounterDto
	9,  // 16: EncounterService.Delete:output_type -> Empty
	8,  // 17: EncounterService.GetAllActive:output_type -> EncounterDtoList
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_encounter_service_proto_init() }
func file_encounter_service_proto_init() {
	if File_encounter_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_encounter_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CoordinateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncounterDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetEncounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEncounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEncounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEncounterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncounterDtoList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_encounter_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_encounter_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_encounter_service_proto_goTypes,
		DependencyIndexes: file_encounter_service_proto_depIdxs,
		EnumInfos:         file_encounter_service_proto_enumTypes,
		MessageInfos:      file_encounter_service_proto_msgTypes,
	}.Build()
	File_encounter_service_proto = out.File
	file_encounter_service_proto_rawDesc = nil
	file_encounter_service_proto_goTypes = nil
	file_encounter_service_proto_depIdxs = nil
}
